// <auto-generated />
namespace Day3__01._25._17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCommentToReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCommentToReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201701251640078_AddCommentToReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
